tap 'homebrew/cask'
tap 'romkatv/powerlevel10k'
tap 'homebrew/cask-fonts'

brew 'asdf'
brew 'mas'
brew 'romkatv/powerlevel10k/powerlevel10k'
brew 'yarn'
brew 'z'
brew 'zstd'

cask 'authy'
cask 'datagrip'
cask 'docker'
cask 'google-chrome'
cask 'hyper'
cask 'intellij-idea'
cask 'lastpass'
cask 'polymail'
cask 'postman'
cask 'slack'
cask 'textmate'
cask 'zoom'
